language: node_js
node_js:
  - "0.10"

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sudo add-apt-repository -y ppa:yandex-qatools/allure-framework
  - sudo apt-get update
  - sudo apt-get install allure-cli
